### ISSUE TITLE
You might like Dplython, pandas-ply, and dfply

### ISSUE THREAD

**Issue by steventsimpson** [koaning/kadro#8]
This is definitely the one thing I miss about R. And Rstudio

**Comment by koaning** [comment]
I made this kind of as a personal project but also because a few things about those packages did not work well for me; 

- i am not a big fan of using an infix `X`. i'd much rather use lambda functions. it feels a bit verbose, but a little bit less 'magical' to me. also ... why not use `_` instead of `X`? 
- the `>>` operator from **dfply** is not a true global operator and will not be very polymorphic. this means that I need to pay attention what functions/methods I can apply. 

These preferences are highly personal but reason enough to make a minimum viable library that scratches my own personal itch. I also like being able to use both my own wrapper but still be able to access to good old normal pandas dataframe should I ever need it.

**Comment by steventsimpson** [comment]
I agree the X is not ideal. I've seen the _ in scala. 

I admire you for doing it. I wish pandas would officially adopt Dplyr-like chaining so I can use those packages at work. 

Well done

~ Steve

Sent via telepathy

**Comment by koaning** [comment]
Pandas historically put a bit more focus on performance (and to be frank, pandas is still impressively fast) but it has aquired a lot of technical debt over the years. I imagine there being a fair amount of willingness from some of the Pandas devs to implement this, but isn't super easy to do on such a large project that so many companies rely on. This is why I think a wrapper that demos functionality might make some more sense. You'll lose very little by doing that. 

I also don't think pandas is the thing in the way of proper dplyr chaining, it is also the python language that isn't as flexible as R in terms of creating operators.
